### ISSUE TITLE
[fix] 회원가입 에러 처리

### ISSUE THREAD

**Issue by choiseoji** [BeautiPong/transcendence-api#33]
## 설명
- 현재 x-www-form 형태만 입력받을 수 있어 json 형태로 입력받도록 수정
- 닉네임, 이메일 중복 방지
- 현재 비밀번호가 null 이어도 회원가입 됨

## TODO
- [x] json으로 읽도록 수정하기
- [x] DB에 닉네임, 이메일이 이미 있는 경우 에러 메시지 반환하기
- [x] 비밀번호 null 이 되지 않도록 수정
