### ISSUE TITLE
[feat] 친구 추가, 수락 기능 구현

### ISSUE THREAD

**Issue by choiseoji** [BeautiPong/transcendence-api#47]
## 설명
- 웹소켓을 사용하여 친구 추가, 수락 기능 구현

## TODO
- [x] 친구 추가 api 만들기
- [x] api에서 받아온 상대방 nickname 그룹으로 메시지 보내기
- [x] 친구 수락 -> ENUM 상태 ACCEPT로 바꿔주기
- [x] 로그인, 로그아웃시  status 바꿔주기
