### ISSUE TITLE
[Fix] 친구 예외처리

### ISSUE THREAD

**Issue by seonmiki** [BeautiPong/transcendence-api#57]
## 설명
- 초대나 친구추가 예외처리

## TODO
- [x] 나 자신에게 친구 추가
- [x] 나 자신에게 게임 초대
- [x] 없는 유저 친구 추가
- [x] 없는 유저 게임 초대
- [x] 오프라인인 친구 게임 초대
